<?xml version="1.0"?>
<package format="2">
  <name>nova_kobuki</name>
  <version>0.1.0</version>
  <description>A optional 'nova' ROS package for control of a Kobuki.</description>
  <maintainer email="wray@cs.umass.edu">Kyle Hollins Wray</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <depend>message_generation</depend>
  <depend>message_runtime</depend>

  <depend>epic</depend>

  <export>
  </export>

</package>
