# This message describes movement in a grid world and assumes
# that the robot's localization is essentially perfect.

# The four primary directions.
uint8 NORTH = 0
uint8 SOUTH = 1
uint8 EAST = 2
uint8 WEST = 3

# The additional four directions.
uint8 NORTH_EAST = 4
uint8 NORTH_WEST = 5
uint8 SOUTH_EAST = 6
uint8 SOUTH_WEST = 7

# The actual action to take from the direction constants above.
uint8 action

# The grid cell size in meters.
float32 grid_cell_size

---

# Respond with the current action being executed, if any.
ActionType current_action

