# This message describes navigation by executing the
# harmonic function path planner 'epic'.

# Specify a vector of points to consider as goals.
geometry_msgs/Point[] points

---

# Respond with the current action being executed, if any.
# This must be from the types listed in the ActionType message.
uint8 current_action

