# This message describes active communication as LED and beeps.

# What LED to show for the Kobuki. These match kobuki_msgs/Led.
uint8 BLACK = 0
uint8 GREEN = 1
uint8 ORANGE = 2
uint8 RED = 3

uint8 led

# What sound to make for the Kobuki. These match kobuki_msgs/Sound.
uint8 ON = 0
uint8 OFF = 1
uint8 RECHARGE = 2
uint8 BUTTON = 3
uint8 ERROR = 4
uint8 CLEANINGSTART = 5
uint8 CLEANINGEND = 6

uint8 sound

# How long to pause (in seconds) before terminating this action.
float32 duration

---

# Respond with the current action being executed, if any.
# This must be from the types listed in the ActionType message.
uint8 current_action

