# This message describes aligning to face an object
# (e.g., AR tag) at a particular distance.

# Which object to face. This is the object UID from
# the map data objects.
uint64 object_uid

# The distance in meters from the object.
float32 distance_from_object

---

# Respond with the current action being executed, if any.
# This must be from the types listed in the ActionType message.
uint8 current_action

